# Connections timeout, in seconds.
timeout = 10

[Websocket]
addr = ":443"

# Origins allowed to use the websocket server.
# If empty or not set, requests from ANY origins are accepted.
origins = [
  "zeroleaks.org",
]

# Optional. If not set, the server will listen for plain
# unencrypted websocket connections.
[Websocket.TLS]
cert = "zeroleaks.crt"
key = "zeroleaks.key"

[DNS]
addr = ":53"

# Domain under which to create temporary subdomains.
domain = "dns.zeroleaks.org"

[BitTorrent]
addr = ":1337"
