# Publicly reachable hostname on which the helper is hosted.
# May be an IP address.
host = "zeroleaks.org"

[Websocket]
# Address on which the websocket server listens.
addr = ":443"

# Origins allowed to use the websocket server.
# If empty or not set, requests from ANY origins are accepted.
origins = [
  "zeroleaks.org",
]

# Optional TLS configuration. If not set, the server will
# listen for plain unencrypted websocket connections.
[Websocket.TLS]
cert = "zeroleaks.crt"
key = "zeroleaks.key"

[DNS]
# Address on which the DNS server listens.
# Must be publicly reachable on port 53.
addr = ":53"

# Session expiration timeout.
timeout = "10s"

# Domain under which to create temporary subdomains.
domain = "dns.zeroleaks.org"

[BitTorrent]
# Address on which the BitTorrent tracker listens.
addr = ":1337"

# Session expiration timeout.
timeout = "5m"
