#!/bin/sh

set -eu

SERVICE="zeroleaks-helper.service"

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask "$SERVICE" >/dev/null || true

	if deb-systemd-helper --quiet was-enabled "$SERVICE"; then
		deb-systemd-helper enable "$SERVICE" >/dev/null || true
	else
		deb-systemd-helper update-state "$SERVICE" >/dev/null || true
	fi

	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
	fi
fi
